#ifndef GDLBUFFER_H
#define	GDLBUFFER_H

class GdlBuffer {
public:
    enum GDLBUFFER_TEXTURE_TYPE {
		GDLBUFFER_TEXTURE_TYPE_ALBEDO,
        GDLBUFFER_TEXTURE_TYPE_DIRECTLIGHT,
        GDLBUFFER_TEXTURE_TYPE_NORMAL,
		GDLBUFFER_NUM_TEXTURES
    };
	static const int GDLBUFFER_TEXTURE_TYPE_DEPTH = GDLBUFFER_NUM_TEXTURES;
	static const int GDLBUFFER_TEXTURE_AVAILABLE  = GDLBUFFER_NUM_TEXTURES+1;

};

#endif

