#ifndef SAAOILGBUFFER_H
#define	SAAOILGBUFFER_H

class SaAoIlGBuffer {
public:
    enum GBUFFER_TEXTURE_TYPE {        
         GBUFFER_TEXTURE_TYPE_ALBEDO,
         GBUFFER_TEXTURE_TYPE_DIRECTLIGHT,
         GBUFFER_TEXTURE_TYPE_NORMAL,
		 GBUFFER_NUM_TEXTURES
    };    
	static const int GBUFFER_TEXTURE_TYPE_DEPTH = GBUFFER_NUM_TEXTURES;
	static const int GBUFFER_TEXTURE_AVAILABLE  = GBUFFER_NUM_TEXTURES+1;   
};

#endif	

