#ifndef SUBROUTINESCONFIG_INC
#define SUBROUTINESCONFIG_INC
//////////////////////////////////////////////////////////////////

//#define USE_SUBROUTINE_RANDOMGENERATOR 1


//#define USE_SUBROUTINE_AOCALCULATOR 1
//#define USE_SUBROUTINE_ILCALCULATOR 1

//#define USE_SUBROUTINE_SAMPLESLOCATOR 1

//#define USE_SUBROUTINE_AREACALCULATOR 1

//////////////////////////////////////////////////////////////////
#endif
